/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { BackgroundSyncPlugin } from 'workbox-background-sync'

declare const self: ServiceWorkerGlobalScope

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])
cleanupOutdatedCaches()

// Cache Google & Custom Web Fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-cache',
  })
)

// Cache Images, SVGs, and Icons
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images-cache',
  })
)

// Cache Media and Static Files from Storage
registerRoute(
  ({ url }) => url.pathname.startsWith('/storage/'),
  new CacheFirst({
    cacheName: 'media-storage-cache',
  })
)

// Network-First with quick timeout for Offline API Calls & Course Data
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/offline') || url.pathname.startsWith('/api/courses') || url.pathname.startsWith('/api/lessons'),
  new NetworkFirst({
    cacheName: 'api-offline-cache',
    networkTimeoutSeconds: 3,
  })
)

// Background Sync for Offline Learning Progress & Quiz Attempts
const bgSync = new BackgroundSyncPlugin('elms-sync', {
  maxRetentionTime: 24 * 60, // Retry for up to 24 hours
})

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/sync'),
  new NetworkFirst({
    plugins: [bgSync],
  }),
  'POST'
)

// Skip Waiting on update
self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

// Claim clients immediately on activation
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})
