<script setup lang="ts">
import { ref } from 'vue'
import { Link } from '@inertiajs/vue3'
import StudentLayout from '@/Layouts/StudentLayout.vue'

const aiAlertsList = ref([
  {
    id: 1,
    type: 'study_reminder',
    icon: '🤖',
    title: 'Study Reminder',
    badge: 'Inactivity Notice',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    description: 'You have not studied for 3 days. Pick up right where you left off in Web Development.',
    target: 'Chapter 3 — JavaScript Functions (53% completed)',
    actionLabel: 'Continue Learning',
    actionHref: '/student/my-courses/current',
    hidden: false
  },
  {
    id: 2,
    type: 'weak_topic',
    icon: '⚠️',
    title: 'Weak Topic Alert',
    badge: 'Urgent Focus',
    badgeColor: 'bg-rose-500/20 text-rose-300 border-rose-500/30',
    description: 'Your performance in JavaScript Functions (62%) needs improvement before advancing to DOM Manipulation.',
    target: 'Recommended: Complete 5 targeted practice questions with AI.',
    actionLabel: 'Practice 5 Questions',
    actionHref: '/student/quizzes/practice',
    secondaryActionLabel: 'Review Lesson',
    secondaryActionHref: '/student/my-courses/current',
    hidden: false
  },
  {
    id: 3,
    type: 'quiz_milestone',
    icon: '📝',
    title: 'Quiz Readiness Milestone',
    badge: 'Ready to Test',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    description: 'You have completed all video and notes for Chapter 3.2. Ready to test your comprehension?',
    target: 'Estimated time: 5 minutes • 5 Questions',
    actionLabel: 'Take Mini Quiz',
    actionHref: '/student/my-courses/current',
    hidden: false
  },
  {
    id: 4,
    type: 'velocity_boost',
    icon: '🚀',
    title: 'Pacing & Velocity Milestone',
    badge: '+15% Ahead',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    description: 'Great momentum! You are 15% ahead of your cohort in JavaScript Syntax exercises.',
    target: 'Target completion date updated to June 15, 2026.',
    actionLabel: 'View Learning Path',
    actionHref: '/student/ai-path/recommended',
    hidden: false
  }
])

const dismissAlert = (id: number) => {
  const item = aiAlertsList.value.find(a => a.id === id)
  if (item) item.hidden = true
}
</script>

<template>
  <StudentLayout
    title="AI Study Alerts & Smart Notifications"
    :breadcrumbs="[
      { label: 'Dashboard', href: '/student/dashboard' },
      { label: 'Notifications', href: '/student/notifications/ai-alerts' },
      { label: 'AI Alerts' }
    ]"
  >
    <div class="space-y-6 pb-12">
      
      <!-- Top Banner -->
      <div class="bg-gradient-to-r from-purple-950 via-slate-900 to-indigo-950 border border-purple-500/30 rounded-3xl p-6 sm:p-8 shadow-2xl flex flex-col md:flex-row md:items-center justify-between gap-6 relative overflow-hidden">
        <div class="space-y-2.5 max-w-2xl">
          <span class="px-3 py-1 rounded-full bg-purple-500/20 text-purple-300 border border-purple-500/40 text-xs font-bold uppercase tracking-wider">
            🤖 AI SMART NOTIFICATIONS
          </span>

          <h1 class="text-2xl sm:text-3xl font-black text-white tracking-tight">
            AI Study Alerts & Proactive Guidance
          </h1>

          <p class="text-xs sm:text-sm text-slate-300 leading-relaxed">
            Real-time proactive triggers generated by the AI engine based on study frequency, quiz gaps, and upcoming assessments.
          </p>
        </div>
      </div>

      <!-- Alerts List -->
      <div class="space-y-4">
        <template v-for="alert in aiAlertsList" :key="alert.id">
          <div
            v-if="!alert.hidden"
            class="bg-slate-900/85 border border-slate-800 hover:border-purple-500/30 rounded-3xl p-5 sm:p-6 shadow-xl space-y-4 transition-all"
          >
            <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
              <div class="flex items-center gap-3">
                <div class="w-10 h-10 rounded-2xl bg-purple-600/20 border border-purple-500/30 flex items-center justify-center text-lg shrink-0">
                  {{ alert.icon }}
                </div>
                <div>
                  <h3 class="text-base font-bold text-white">{{ alert.title }}</h3>
                  <p class="text-xs text-slate-400 mt-0.5">{{ alert.description }}</p>
                </div>
              </div>

              <span :class="[alert.badgeColor, 'px-3 py-1 rounded-full text-xs font-bold border self-start sm:self-auto shrink-0']">
                {{ alert.badge }}
              </span>
            </div>

            <!-- Target info box -->
            <div class="p-3.5 rounded-2xl bg-slate-950/70 border border-slate-800/80 text-xs text-slate-300 flex items-center justify-between">
              <span class="font-medium">{{ alert.target }}</span>
            </div>

            <!-- Action Buttons Footer -->
            <div class="flex items-center justify-between pt-1">
              <button
                @click="dismissAlert(alert.id)"
                type="button"
                class="text-xs text-slate-500 hover:text-slate-300 transition-colors cursor-pointer"
              >
                Dismiss
              </button>

              <div class="flex items-center gap-2.5">
                <Link
                  v-if="alert.secondaryActionHref"
                  :href="alert.secondaryActionHref"
                  class="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-bold border border-slate-700 transition-colors"
                >
                  {{ alert.secondaryActionLabel }}
                </Link>
                <Link
                  :href="alert.actionHref"
                  class="px-5 py-2 rounded-xl bg-purple-600 hover:bg-purple-500 text-white text-xs font-bold shadow-lg shadow-purple-600/30 transition-all hover:scale-105 active:scale-95"
                >
                  {{ alert.actionLabel }} →
                </Link>
              </div>
            </div>
          </div>
        </template>
      </div>

    </div>
  </StudentLayout>
</template>
